server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:example@mongodb:27017/db?authSource=admin

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

notification:
  service:
    url: http://NOTIFICATION-SERVICE/api/notify

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

