server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  zipkin:
    base-url: http://zipkin:9411/
    sender-type: web
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: book-service-route
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/books/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: bookServiceCB
                    fallbackUri: forward:/fallback/books
                - name: Retry
                  args:
                    retries: 3
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                    methods: POST, PUT, PATCH
                    exceptions: java.io.IOException
                - name: Bulkhead
                  args:
                    name: bookServiceBulkhead
                    maxConcurrentCalls: 5
                    maxWaitDuration: 0s
                - JwtAuthenticationFilter
            - id: notification-service-route
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notify/**
            - id: auth-login-limit
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/login
                - Method=POST
              filters:
                - LoginRateLimitFilter
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**

resilience4j:
  circuitbreaker:
    instances:
      bookServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true

logging:
  level:
    org.springframework.cloud.gateway: INFO