server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: book-service-route
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/books/**
              filters:
                - JwtAuthenticationFilter
            - id: notification-service-route
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notify/**
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 5
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"
logging:
  level:
    org.springframework.cloud.gateway: INFO