server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  kafka:
    consumer:
      group-id: notification-service-group
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/db?authSource=admin