server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/db?authSource=admin
  kafka:
    consumer:
      group-id: notification-service-group
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"